service: serverless-smooch-abc-templater

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 45 # optional, in seconds, default is 6
  name: aws
  runtime: nodejs6.10
  environment:

functions:
  templater:
    handler: handler.endpoint
    events:
      - http:
          path: event
          method: post
